### ISSUE TITLE
Error generating static site when adding lazy loading routes 

### ISSUE THREAD

**Issue by mbaljeetsingh** [chrisguttandin/angular-prerender#82]
**Error**
![image](https://user-images.githubusercontent.com/872762/64906431-21e4e200-d704-11e9-8a71-940e1cbb5af0.png)

**Steps to reproduce**

1. `npx @angular/cli new ng-static --routing`

2. `ng generate universal --client-project ng-static`

3. Create lazy route
![image](https://user-images.githubusercontent.com/872762/64906378-99664180-d703-11e9-8b82-a1e1975a6265.png)

4. `ng build`
![image](https://user-images.githubusercontent.com/872762/64906423-0548aa00-d704-11e9-952f-f9657d6f651b.png)

5. `ng run ng-static:server`
![image](https://user-images.githubusercontent.com/872762/64906424-0b3e8b00-d704-11e9-94f0-152ab808a1df.png)

6. `npx angular-prerender`
![image](https://user-images.githubusercontent.com/872762/64906428-17c2e380-d704-11e9-9526-f04816da6f75.png)

**Comment by chrisguttandin** [comment]
Hi @mbaljeetsingh, thanks for reporting this. I was almost about to ask you to create an issue with the error you ran into in the [other thread](angular/angular/issues/23024).

I tried to reproduce the problem. I got a different error when using angular-prerender via npx. I therefore installed it as local dev dependency and then it worked as expected.

Can you please try installing it as a local dependency and report back if that solves the problem? Many thanks in advance.

**Comment by mbaljeetsingh** [comment]
I tried installing it as a dev dependency. But it is not recognizing angular-prerender command. Not sure why. That's why I was using npx

**Comment by chrisguttandin** [comment]
Okay, that's indeed a little strange. Just to be sure we talk about the same thing. When you run the following commands you get an error which says the command angular-prerender couldn't be found?

```shell
npx @angular/cli new ng-static --routing
cd ng-static
ng generate universal --client-project ng-static
ng generate module lazy --route lazy --module app
npm install angular-prerender --save-dev
ng build
ng run ng-static:server
angular-prerender
```

Does a direct invocation work?

```shell
node node_modules/.bin/angular-prerender
```

**Comment by mbaljeetsingh** [comment]
Yes, I get angular-prerender not found when I follow these steps.

I'll confirm the direct invocation tomorrow.

**Comment by chrisguttandin** [comment]
Alright many thanks in advance.

Another thing which works for me is using npx like this: `npx --package @angular/core angular-prerender`.

**Comment by mbaljeetsingh** [comment]
Hi, 

With direct invocation, I'm getting the following error
`node node_modules/.bin/angular-prerender`
![image](https://user-images.githubusercontent.com/872762/64915823-b182a300-d78d-11e9-9a48-f2fd58078bf3.png)

**Comment by mbaljeetsingh** [comment]
> Alright many thanks in advance.
> 
> Another thing which works for me is using npx like this: `npx --package @angular/core --package angular-prerender --package rxjs angular-prerender`.

This seems to be working.
![image](https://user-images.githubusercontent.com/872762/64915868-9b291700-d78e-11e9-8f94-7b8df09132cc.png)

**Comment by mbaljeetsingh** [comment]
As a side note, I have deployed the site to netlify with the following build command 
`ng build && ng run ng-static:server && npx angular-prerender`
It seems to be working there. It is most probably the issue with windows or my machine.

**Website Link**
[https://cocky-turing-e48324.netlify.com/lazy](https://cocky-turing-e48324.netlify.com/lazy)

**Comment by chrisguttandin** [comment]
Thanks for testing the different options.

To be honest I have no idea why you get the error when you invoke the command directly. The code that threw the error is somewhere deep inside the internals of Node.js. Which version of Node.js are you using? I run the tests for v10 and v12 but only on Linux and macOS.

I certainly have to update the `npx` usage in the README. I think I forgot to update it when I defined @angular/core as a peer dependency.

**Comment by mbaljeetsingh** [comment]
`node version` is _10.16.3_
![image](https://user-images.githubusercontent.com/872762/64919559-0f34e080-d7ca-11e9-9d56-e80976bf713d.png)

**Comment by chrisguttandin** [comment]
Thank you. I think I found the reason why `npx angular-prerender` doesn't work anymore. @angular/core is a peer dependency of angular-prerender and @nguniversal/module-map-ngfactory-loader is a regular dependency. But @nguniversal/module-map-ngfactory-loader also requires @angular/core. I tried to fix it with the latest patch but unfortunately it doesn't work out.

**Comment by chrisguttandin** [comment]
Hi @mbaljeetsingh, I think I fixed the problem now. Using npx without any arguments like this `npx angular-prerender` should work again.

Many thanks for making me aware of that bug. Please let me know if you notice any other issues.

**Comment by mbaljeetsingh** [comment]
Hi @chrisguttandin, It seems to working now. Thanks
But I'm still not sure why it is not working when adding it as dev dependency. I tried using WSL (ubuntu) too, getting the same error there.

**Comment by chrisguttandin** [comment]
Thanks for trying it on a different machine as well. The error that you're getting is the one which says that the command could not be found, right?

Does the direct invocation (`node node_modules/.bin/angular-prerender`) work? 

Do other local commands work? I guess running `ng ...` works. Is the Angular CLI also only installed locally or do you have it installed globally as well? You can check this by running `npm ls @angular/cli --global`.

**Comment by mbaljeetsingh** [comment]
Yes, I'm getting _command not found_

- direct invocation `node node_modules/.bin/angular-prerender` is working on Ubuntu, but not on Windows.
- Saving as dev dependency is not working on either platform (Ubuntu & Windows).
- `npx angular-prerender` is working on both ubuntu and windows

Yes, other local commands are working fine for me.

**Comment by chrisguttandin** [comment]
Thanks a lot for doing all those checks.

I meanwhile found out that [npm's documentation](https://docs.npmjs.com/files/package.json#bin) always uses a relative path to specify the bin property. The Angular CLI (https://github.com/angular/angular-cli/blob/master/package.json#L6) does that as well. I therefore updated the package.json of angular-prerender to also use a relative path: https://github.com/chrisguttandin/angular-prerender/commit/4aabec6f70187d7e1222dd3676c9fc825fe0a919.

Can you please check one more time if that makes the command work when angular-prerender (v4.1.12) is dev dependency? Many thanks in advance.

**Comment by mbaljeetsingh** [comment]
Hi @chrisguttandin,

I'm still getting the same error in v4.1.12

**Comment by mbaljeetsingh** [comment]
Hi @chrisguttandin 

I'm getting the same error in v4.1.12

**Comment by chrisguttandin** [comment]
Thanks @mbaljeetsingh, I will keep on investigating.

**Comment by chrisguttandin** [comment]
Hi @mbaljeetsingh, I think I was wrong. Thanks to the help of @kroeder and the friendly people in the Angular.de Slack I'm pretty sure now that running a locally installed command only works on OS X. On Windows it either has to be installed globally or it should be used with npx.

I updated the README to reflect that.

Many thanks again for making me aware of this and please let me know if you run into any further issues.
